language: go
go:
  - 1.9
  - tip
compiler:
  - g++
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libtesseract-dev libleptonica-dev tesseract-ocr-eng
env:
  - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
install:
  - go get -t -v ./...
script:
  - go test ./... -cover
